<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registrasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Registrasi_model');

    } 

    /*
     * Listing of registrasi
     */
    function index()
    {
        $data['registrasi'] = $this->Registrasi_model->get_all_registrasi();
		$data['total_registrasi'] = $this->Registrasi_model->total_rows();
		
        $data['_view'] = 'registrasi/index';
        $this->load->view('layouts/main',$data);

	
    }

    /*
     * Adding a new registrasi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jenis_kendaraan' => $this->input->post('jenis_kendaraan'),
				'tanggal_kunjungan' => $this->input->post('tanggal_kunjungan'),
				'pemeriksaan' => $this->input->post('pemeriksaan'),
				'jenis_pasien' => $this->input->post('jenis_pasien'),
				'nomor_identitas' => $this->input->post('nomor_identitas'),
				'nama' => $this->input->post('nama'),
				'tanggal_lahir' => $this->input->post('tanggal_lahir'),
				'telpon' => $this->input->post('telpon'),
				'jenis_kelamin' => $this->input->post('jenis_kelamin'),
				'kecamatan' => $this->input->post('kecamatan'),
				'kelurahan' => $this->input->post('kelurahan'),
				'kota' => $this->input->post('kota'),
				'negara' => $this->input->post('negara'),
				'datang' => $this->input->post('datang'),
				'tujuan' => $this->input->post('tujuan'),
				'keberangkatan' => $this->input->post('keberangkatan'),
				'maskapai' => $this->input->post('maskapai'),
				'awal_gejala' => $this->input->post('awal_gejala'),
				'demam' => $this->input->post('demam'),
				'menggigil' => $this->input->post('menggigil'),
				'sakit_kepala' => $this->input->post('sakit_kepala'),
				'abdomen' => $this->input->post('abdomen'),
				'batuk' => $this->input->post('batuk'),
				'pilek' => $this->input->post('pilek'),
				'sesak_nafas' => $this->input->post('sesak_nafas'),
				'tenggorokan' => $this->input->post('tenggorokan'),
				'diare' => $this->input->post('diare'),
				'lemas' => $this->input->post('lemas'),
				'nyeri_otot' => $this->input->post('nyeri_otot'),
				'mual' => $this->input->post('mual'),
				'hamil' => $this->input->post('hamil'),
				'diabetes' => $this->input->post('diabetes'),
				'penyakit_jantung' => $this->input->post('penyakit_jantung'),
				'hipertensi' => $this->input->post('hipertensi'),
				'keganasan' => $this->input->post('keganasan'),
				'imunologi' => $this->input->post('imunologi'),
				'ginjal_kronis' => $this->input->post('ginjal_kronis'),
				'gagal_hati' => $this->input->post('gagal_hati'),
				'ppok' => $this->input->post('ppok'),
				'faktor1' => $this->input->post('faktor1'),
				'faktor2' => $this->input->post('faktor2'),
				'faktor3' => $this->input->post('faktor3'),
				'faktor4' => $this->input->post('faktor4'),
				'faktor5' => $this->input->post('faktor5'),
				'faktor6' => $this->input->post('faktor6'),
				'faktor7' => $this->input->post('faktor7'),
				'status_pengerjaan' => $this->input->post('status_pengerjaan'),
				'status_bayar' => $this->input->post('status_bayar'),
				'alamat' => $this->input->post('alamat'),
            );
            
            $registrasi_id = $this->Registrasi_model->add_registrasi($params);
            redirect('registrasi/index');
        }
        else
        {            
            $data['_view'] = 'registrasi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a registrasi
     */
    function edit($no_boking)
    {   
        // check if the registrasi exists before trying to edit it
        $data['registrasi'] = $this->Registrasi_model->get_registrasi($no_boking);
        
        if(isset($data['registrasi']['no_boking']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jenis_kendaraan' => $this->input->post('jenis_kendaraan'),
					'tanggal_kunjungan' => $this->input->post('tanggal_kunjungan'),
					'pemeriksaan' => $this->input->post('pemeriksaan'),
					'jenis_pasien' => $this->input->post('jenis_pasien'),
					'nomor_identitas' => $this->input->post('nomor_identitas'),
					'nama' => $this->input->post('nama'),
					'tanggal_lahir' => $this->input->post('tanggal_lahir'),
					'telpon' => $this->input->post('telpon'),
					'jenis_kelamin' => $this->input->post('jenis_kelamin'),
					'kecamatan' => $this->input->post('kecamatan'),
					'kelurahan' => $this->input->post('kelurahan'),
					'kota' => $this->input->post('kota'),
					'negara' => $this->input->post('negara'),
					'datang' => $this->input->post('datang'),
					'tujuan' => $this->input->post('tujuan'),
					'keberangkatan' => $this->input->post('keberangkatan'),
					'maskapai' => $this->input->post('maskapai'),
					'awal_gejala' => $this->input->post('awal_gejala'),
					'demam' => $this->input->post('demam'),
					'menggigil' => $this->input->post('menggigil'),
					'sakit_kepala' => $this->input->post('sakit_kepala'),
					'abdomen' => $this->input->post('abdomen'),
					'batuk' => $this->input->post('batuk'),
					'pilek' => $this->input->post('pilek'),
					'sesak_nafas' => $this->input->post('sesak_nafas'),
					'tenggorokan' => $this->input->post('tenggorokan'),
					'diare' => $this->input->post('diare'),
					'lemas' => $this->input->post('lemas'),
					'nyeri_otot' => $this->input->post('nyeri_otot'),
					'mual' => $this->input->post('mual'),
					'hamil' => $this->input->post('hamil'),
					'diabetes' => $this->input->post('diabetes'),
					'penyakit_jantung' => $this->input->post('penyakit_jantung'),
					'hipertensi' => $this->input->post('hipertensi'),
					'keganasan' => $this->input->post('keganasan'),
					'imunologi' => $this->input->post('imunologi'),
					'ginjal_kronis' => $this->input->post('ginjal_kronis'),
					'gagal_hati' => $this->input->post('gagal_hati'),
					'ppok' => $this->input->post('ppok'),
					'faktor1' => $this->input->post('faktor1'),
					'faktor2' => $this->input->post('faktor2'),
					'faktor3' => $this->input->post('faktor3'),
					'faktor4' => $this->input->post('faktor4'),
					'faktor5' => $this->input->post('faktor5'),
					'faktor6' => $this->input->post('faktor6'),
					'faktor7' => $this->input->post('faktor7'),
					'status_pengerjaan' => $this->input->post('status_pengerjaan'),
					'status_bayar' => $this->input->post('status_bayar'),
					'alamat' => $this->input->post('alamat'),
                );

                $this->Registrasi_model->update_registrasi($no_boking,$params);            
                redirect('registrasi/index');
            }
            else
            {
                $data['_view'] = 'registrasi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The registrasi you are trying to edit does not exist.');
    } 

    /*
     * Deleting registrasi
     */
    function remove($no_boking)
    {
        $registrasi = $this->Registrasi_model->get_registrasi($no_boking);

        // check if the registrasi exists before trying to delete it
        if(isset($registrasi['no_boking']))
        {
            $this->Registrasi_model->delete_registrasi($no_boking);
            redirect('registrasi/index');
        }
        else
            show_error('The registrasi you are trying to delete does not exist.');
    }
    
}
