<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registrasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get registrasi by no_boking
     */
    function get_registrasi($no_boking)
    {
        return $this->db->get_where('registrasi',array('no_boking'=>$no_boking))->row_array();
    }
        
    /*
     * Get all registrasi
     */
    function get_all_registrasi()
    {
        $this->db->order_by('no_boking', 'desc');
        return $this->db->get('registrasi')->result_array();
    }
        
    /*
     * function to add new registrasi
     */
    function add_registrasi($params)
    {
        $this->db->insert('registrasi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update registrasi
     */
    function update_registrasi($no_boking,$params)
    {
        $this->db->where('no_boking',$no_boking);
        return $this->db->update('registrasi',$params);
    }
    
    /*
     * function to delete registrasi
     */
    function delete_registrasi($no_boking)
    {
        return $this->db->delete('registrasi',array('no_boking'=>$no_boking));
    }

    function total_rows() {
        return $this->db->get('registrasi')->num_rows();
      }
}
